apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # since we do not want auth service to be public facing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
